/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.25
 */

#include "sipAPIlibqt_gui_cpp_sip.h"

#line 8 "recursive_plugin_provider.sip"
#include <qt_gui_cpp/recursive_plugin_provider.h>
#line 12 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"

#line 9 "ros_pluginlib_plugin_provider_for_plugin_providers.sip"
#include <qt_gui_cpp/ros_pluginlib_plugin_provider_for_plugin_providers.h>
#line 16 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 27 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qpycore_qmap.sip"
#include <qmap.h>
#line 19 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 27 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qstring.sip"
#include <qstring.h>
#line 22 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 28 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qobject.sip"
#include <qobject.h>
#line 25 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 8 "plugin.sip"
#include <qt_gui_cpp/plugin.h>
#line 28 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 7 "plugin_context.sip"
#include <qt_gui_cpp/plugin_context.h>
#line 31 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 149 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 34 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 7 "plugin_descriptor.sip"
#include <qt_gui_cpp/plugin_descriptor.h>
#line 37 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 149 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 40 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"
#line 7 "plugin_provider.sip"
#include <qt_gui_cpp/plugin_provider.h>
#line 43 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppRecursivePluginProvider.cpp"


class sipqt_gui_cpp_RecursivePluginProvider : public  ::qt_gui_cpp::RecursivePluginProvider
{
public:
    sipqt_gui_cpp_RecursivePluginProvider( ::qt_gui_cpp::RosPluginlibPluginProvider_ForPluginProviders*);
    sipqt_gui_cpp_RecursivePluginProvider(const  ::qt_gui_cpp::RecursivePluginProvider&);
    virtual ~sipqt_gui_cpp_RecursivePluginProvider();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void shutdown() SIP_OVERRIDE;
    void unload_plugin( ::qt_gui_cpp::Plugin*) SIP_OVERRIDE;
    void unload(void*) SIP_OVERRIDE;
     ::qt_gui_cpp::Plugin* load_plugin(const  ::QString&, ::qt_gui_cpp::PluginContext*) SIP_OVERRIDE;
    void* load(const  ::QString&, ::qt_gui_cpp::PluginContext*) SIP_OVERRIDE;
    QList< ::qt_gui_cpp::PluginDescriptor*> discover_descriptors( ::QObject*) SIP_OVERRIDE;
    QMap< ::QString, ::QString> discover( ::QObject*) SIP_OVERRIDE;
    void set_plugin_providers(const QList< ::qt_gui_cpp::PluginProvider*>&) SIP_OVERRIDE;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipqt_gui_cpp_RecursivePluginProvider(const sipqt_gui_cpp_RecursivePluginProvider &);
    sipqt_gui_cpp_RecursivePluginProvider &operator = (const sipqt_gui_cpp_RecursivePluginProvider &);

    char sipPyMethods[8];
};

sipqt_gui_cpp_RecursivePluginProvider::sipqt_gui_cpp_RecursivePluginProvider( ::qt_gui_cpp::RosPluginlibPluginProvider_ForPluginProviders*a0):  ::qt_gui_cpp::RecursivePluginProvider(a0), sipPySelf(SIP_NULLPTR)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipqt_gui_cpp_RecursivePluginProvider::sipqt_gui_cpp_RecursivePluginProvider(const  ::qt_gui_cpp::RecursivePluginProvider& a0):  ::qt_gui_cpp::RecursivePluginProvider(a0), sipPySelf(SIP_NULLPTR)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipqt_gui_cpp_RecursivePluginProvider::~sipqt_gui_cpp_RecursivePluginProvider()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

void sipqt_gui_cpp_RecursivePluginProvider::shutdown()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,SIP_NULLPTR,sipName_shutdown);

    if (!sipMeth)
    {
         ::qt_gui_cpp::RecursivePluginProvider::shutdown();
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_6(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    sipVH_libqt_gui_cpp_sip_6(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

void sipqt_gui_cpp_RecursivePluginProvider::unload_plugin( ::qt_gui_cpp::Plugin*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,SIP_NULLPTR,sipName_unload_plugin);

    if (!sipMeth)
    {
         ::qt_gui_cpp::RecursivePluginProvider::unload_plugin(a0);
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_5(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::qt_gui_cpp::Plugin*);

    sipVH_libqt_gui_cpp_sip_5(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipqt_gui_cpp_RecursivePluginProvider::unload(void*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,SIP_NULLPTR,sipName_unload);

    if (!sipMeth)
    {
         ::qt_gui_cpp::RecursivePluginProvider::unload(a0);
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, void*);

    sipVH_libqt_gui_cpp_sip_4(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

 ::qt_gui_cpp::Plugin* sipqt_gui_cpp_RecursivePluginProvider::load_plugin(const  ::QString& a0, ::qt_gui_cpp::PluginContext*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,SIP_NULLPTR,sipName_load_plugin);

    if (!sipMeth)
        return  ::qt_gui_cpp::RecursivePluginProvider::load_plugin(a0,a1);

    extern  ::qt_gui_cpp::Plugin* sipVH_libqt_gui_cpp_sip_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QString&, ::qt_gui_cpp::PluginContext*);

    return sipVH_libqt_gui_cpp_sip_3(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

void* sipqt_gui_cpp_RecursivePluginProvider::load(const  ::QString& a0, ::qt_gui_cpp::PluginContext*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,SIP_NULLPTR,sipName_load);

    if (!sipMeth)
        return  ::qt_gui_cpp::RecursivePluginProvider::load(a0,a1);

    extern void* sipVH_libqt_gui_cpp_sip_2(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QString&, ::qt_gui_cpp::PluginContext*);

    return sipVH_libqt_gui_cpp_sip_2(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

QList< ::qt_gui_cpp::PluginDescriptor*> sipqt_gui_cpp_RecursivePluginProvider::discover_descriptors( ::QObject*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,SIP_NULLPTR,sipName_discover_descriptors);

    if (!sipMeth)
        return  ::qt_gui_cpp::RecursivePluginProvider::discover_descriptors(a0);

    extern QList< ::qt_gui_cpp::PluginDescriptor*> sipVH_libqt_gui_cpp_sip_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*);

    return sipVH_libqt_gui_cpp_sip_1(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

QMap< ::QString, ::QString> sipqt_gui_cpp_RecursivePluginProvider::discover( ::QObject*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,SIP_NULLPTR,sipName_discover);

    if (!sipMeth)
        return  ::qt_gui_cpp::RecursivePluginProvider::discover(a0);

    extern QMap< ::QString, ::QString> sipVH_libqt_gui_cpp_sip_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*);

    return sipVH_libqt_gui_cpp_sip_0(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipqt_gui_cpp_RecursivePluginProvider::set_plugin_providers(const QList< ::qt_gui_cpp::PluginProvider*>& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,SIP_NULLPTR,sipName_set_plugin_providers);

    if (!sipMeth)
    {
         ::qt_gui_cpp::RecursivePluginProvider::set_plugin_providers(a0);
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QList< ::qt_gui_cpp::PluginProvider*>&);

    sipVH_libqt_gui_cpp_sip_7(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}


extern "C" {static PyObject *meth_qt_gui_cpp_RecursivePluginProvider_discover(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_RecursivePluginProvider_discover(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QObject* a0;
         ::qt_gui_cpp::RecursivePluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_qt_gui_cpp_RecursivePluginProvider, &sipCpp, sipType_QObject, &a0))
        {
            QMap< ::QString, ::QString>*sipRes;

            sipRes = new QMap< ::QString, ::QString>((sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::RecursivePluginProvider::discover(a0) : sipCpp->discover(a0)));

            return sipConvertFromNewType(sipRes,sipType_QMap_0100QString_0100QString,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_RecursivePluginProvider, sipName_discover, SIP_NULLPTR);

    return SIP_NULLPTR;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_qt_gui_cpp_RecursivePluginProvider(void *, const sipTypeDef *);}
static void *cast_qt_gui_cpp_RecursivePluginProvider(void *sipCppV, const sipTypeDef *targetType)
{
     ::qt_gui_cpp::RecursivePluginProvider *sipCpp = reinterpret_cast< ::qt_gui_cpp::RecursivePluginProvider *>(sipCppV);

    if (targetType == sipType_qt_gui_cpp_CompositePluginProvider)
        return static_cast< ::qt_gui_cpp::CompositePluginProvider *>(sipCpp);

    if (targetType == sipType_qt_gui_cpp_PluginProvider)
        return static_cast< ::qt_gui_cpp::PluginProvider *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_qt_gui_cpp_RecursivePluginProvider(void *, int);}
static void release_qt_gui_cpp_RecursivePluginProvider(void *sipCppV, int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipqt_gui_cpp_RecursivePluginProvider *>(sipCppV);
    else
        delete reinterpret_cast< ::qt_gui_cpp::RecursivePluginProvider *>(sipCppV);
}


extern "C" {static void assign_qt_gui_cpp_RecursivePluginProvider(void *, SIP_SSIZE_T, void *);}
static void assign_qt_gui_cpp_RecursivePluginProvider(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::qt_gui_cpp::RecursivePluginProvider *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::qt_gui_cpp::RecursivePluginProvider *>(sipSrc);
}


extern "C" {static void *copy_qt_gui_cpp_RecursivePluginProvider(const void *, SIP_SSIZE_T);}
static void *copy_qt_gui_cpp_RecursivePluginProvider(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::qt_gui_cpp::RecursivePluginProvider(reinterpret_cast<const  ::qt_gui_cpp::RecursivePluginProvider *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_qt_gui_cpp_RecursivePluginProvider(sipSimpleWrapper *);}
static void dealloc_qt_gui_cpp_RecursivePluginProvider(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipqt_gui_cpp_RecursivePluginProvider *>(sipGetAddress(sipSelf))->sipPySelf = SIP_NULLPTR;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_qt_gui_cpp_RecursivePluginProvider(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_qt_gui_cpp_RecursivePluginProvider(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_qt_gui_cpp_RecursivePluginProvider(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipqt_gui_cpp_RecursivePluginProvider *sipCpp = SIP_NULLPTR;

    {
         ::qt_gui_cpp::RosPluginlibPluginProvider_ForPluginProviders* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J8", sipType_qt_gui_cpp_RosPluginlibPluginProvider_ForPluginProviders, &a0))
        {
            sipCpp = new sipqt_gui_cpp_RecursivePluginProvider(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::qt_gui_cpp::RecursivePluginProvider* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_qt_gui_cpp_RecursivePluginProvider, &a0))
        {
            sipCpp = new sipqt_gui_cpp_RecursivePluginProvider(*a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_qt_gui_cpp_RecursivePluginProvider[] = {{4, 255, 1}};


static PyMethodDef methods_qt_gui_cpp_RecursivePluginProvider[] = {
    {SIP_MLNAME_CAST(sipName_discover), meth_qt_gui_cpp_RecursivePluginProvider_discover, METH_VARARGS, SIP_NULLPTR}
};


static pyqt5ClassPluginDef plugin_qt_gui_cpp_RecursivePluginProvider = {
    SIP_NULLPTR,
    0,
    SIP_NULLPTR,
    SIP_NULLPTR
};


sipClassTypeDef sipTypeDef_libqt_gui_cpp_sip_qt_gui_cpp_RecursivePluginProvider = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_qt_gui_cpp__RecursivePluginProvider,
        {SIP_NULLPTR},
        &plugin_qt_gui_cpp_RecursivePluginProvider
    },
    {
        sipNameNr_RecursivePluginProvider,
        {3, 255, 0},
        1, methods_qt_gui_cpp_RecursivePluginProvider,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    SIP_NULLPTR,
    -1,
    -1,
    supers_qt_gui_cpp_RecursivePluginProvider,
    SIP_NULLPTR,
    init_type_qt_gui_cpp_RecursivePluginProvider,
    SIP_NULLPTR,
    SIP_NULLPTR,
#if PY_MAJOR_VERSION >= 3
    SIP_NULLPTR,
    SIP_NULLPTR,
#else
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
#endif
    dealloc_qt_gui_cpp_RecursivePluginProvider,
    assign_qt_gui_cpp_RecursivePluginProvider,
    SIP_NULLPTR,
    copy_qt_gui_cpp_RecursivePluginProvider,
    release_qt_gui_cpp_RecursivePluginProvider,
    cast_qt_gui_cpp_RecursivePluginProvider,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
