/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.25
 */

#include "sipAPIlibqt_gui_cpp_sip.h"

#line 7 "plugin_provider.sip"
#include <qt_gui_cpp/plugin_provider.h>
#line 12 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"

#line 8 "plugin.sip"
#include <qt_gui_cpp/plugin.h>
#line 16 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"
#line 27 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qstring.sip"
#include <qstring.h>
#line 19 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"
#line 7 "plugin_context.sip"
#include <qt_gui_cpp/plugin_context.h>
#line 22 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"
#line 149 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 25 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"
#line 7 "plugin_descriptor.sip"
#include <qt_gui_cpp/plugin_descriptor.h>
#line 28 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"
#line 28 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qobject.sip"
#include <qobject.h>
#line 31 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"
#line 27 "/usr/lib/python3/dist-packages/PyQt5/bindings/QtCore/qpycore_qmap.sip"
#include <qmap.h>
#line 34 "/home/f1tenthteam2/pleasework/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginProvider.cpp"


class sipqt_gui_cpp_PluginProvider : public  ::qt_gui_cpp::PluginProvider
{
public:
    sipqt_gui_cpp_PluginProvider();
    sipqt_gui_cpp_PluginProvider(const  ::qt_gui_cpp::PluginProvider&);
    virtual ~sipqt_gui_cpp_PluginProvider();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void shutdown() SIP_OVERRIDE;
    void unload_plugin( ::qt_gui_cpp::Plugin*) SIP_OVERRIDE;
    void unload(void*) SIP_OVERRIDE;
     ::qt_gui_cpp::Plugin* load_plugin(const  ::QString&, ::qt_gui_cpp::PluginContext*) SIP_OVERRIDE;
    void* load(const  ::QString&, ::qt_gui_cpp::PluginContext*) SIP_OVERRIDE;
    QList< ::qt_gui_cpp::PluginDescriptor*> discover_descriptors( ::QObject*) SIP_OVERRIDE;
    QMap< ::QString, ::QString> discover( ::QObject*) SIP_OVERRIDE;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipqt_gui_cpp_PluginProvider(const sipqt_gui_cpp_PluginProvider &);
    sipqt_gui_cpp_PluginProvider &operator = (const sipqt_gui_cpp_PluginProvider &);

    char sipPyMethods[7];
};

sipqt_gui_cpp_PluginProvider::sipqt_gui_cpp_PluginProvider():  ::qt_gui_cpp::PluginProvider(), sipPySelf(SIP_NULLPTR)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipqt_gui_cpp_PluginProvider::sipqt_gui_cpp_PluginProvider(const  ::qt_gui_cpp::PluginProvider& a0):  ::qt_gui_cpp::PluginProvider(a0), sipPySelf(SIP_NULLPTR)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipqt_gui_cpp_PluginProvider::~sipqt_gui_cpp_PluginProvider()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

void sipqt_gui_cpp_PluginProvider::shutdown()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,SIP_NULLPTR,sipName_shutdown);

    if (!sipMeth)
    {
         ::qt_gui_cpp::PluginProvider::shutdown();
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_6(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    sipVH_libqt_gui_cpp_sip_6(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

void sipqt_gui_cpp_PluginProvider::unload_plugin( ::qt_gui_cpp::Plugin*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,SIP_NULLPTR,sipName_unload_plugin);

    if (!sipMeth)
    {
         ::qt_gui_cpp::PluginProvider::unload_plugin(a0);
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_5(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::qt_gui_cpp::Plugin*);

    sipVH_libqt_gui_cpp_sip_5(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipqt_gui_cpp_PluginProvider::unload(void*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,SIP_NULLPTR,sipName_unload);

    if (!sipMeth)
    {
         ::qt_gui_cpp::PluginProvider::unload(a0);
        return;
    }

    extern void sipVH_libqt_gui_cpp_sip_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, void*);

    sipVH_libqt_gui_cpp_sip_4(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

 ::qt_gui_cpp::Plugin* sipqt_gui_cpp_PluginProvider::load_plugin(const  ::QString& a0, ::qt_gui_cpp::PluginContext*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,SIP_NULLPTR,sipName_load_plugin);

    if (!sipMeth)
        return  ::qt_gui_cpp::PluginProvider::load_plugin(a0,a1);

    extern  ::qt_gui_cpp::Plugin* sipVH_libqt_gui_cpp_sip_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QString&, ::qt_gui_cpp::PluginContext*);

    return sipVH_libqt_gui_cpp_sip_3(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

void* sipqt_gui_cpp_PluginProvider::load(const  ::QString& a0, ::qt_gui_cpp::PluginContext*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,SIP_NULLPTR,sipName_load);

    if (!sipMeth)
        return  ::qt_gui_cpp::PluginProvider::load(a0,a1);

    extern void* sipVH_libqt_gui_cpp_sip_2(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QString&, ::qt_gui_cpp::PluginContext*);

    return sipVH_libqt_gui_cpp_sip_2(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

QList< ::qt_gui_cpp::PluginDescriptor*> sipqt_gui_cpp_PluginProvider::discover_descriptors( ::QObject*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,SIP_NULLPTR,sipName_discover_descriptors);

    if (!sipMeth)
        return  ::qt_gui_cpp::PluginProvider::discover_descriptors(a0);

    extern QList< ::qt_gui_cpp::PluginDescriptor*> sipVH_libqt_gui_cpp_sip_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*);

    return sipVH_libqt_gui_cpp_sip_1(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

QMap< ::QString, ::QString> sipqt_gui_cpp_PluginProvider::discover( ::QObject*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,SIP_NULLPTR,sipName_discover);

    if (!sipMeth)
        return  ::qt_gui_cpp::PluginProvider::discover(a0);

    extern QMap< ::QString, ::QString> sipVH_libqt_gui_cpp_sip_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*);

    return sipVH_libqt_gui_cpp_sip_0(sipGILState, sipImportedVirtErrorHandlers_libqt_gui_cpp_sip_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_discover(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_discover(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QObject* a0;
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp, sipType_QObject, &a0))
        {
            QMap< ::QString, ::QString>*sipRes;

            sipRes = new QMap< ::QString, ::QString>((sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::discover(a0) : sipCpp->discover(a0)));

            return sipConvertFromNewType(sipRes,sipType_QMap_0100QString_0100QString,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_discover, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_discover_descriptors(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_discover_descriptors(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QObject* a0;
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp, sipType_QObject, &a0))
        {
            QList< ::qt_gui_cpp::PluginDescriptor*>*sipRes;

            sipRes = new QList< ::qt_gui_cpp::PluginDescriptor*>((sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::discover_descriptors(a0) : sipCpp->discover_descriptors(a0)));

            return sipConvertFromNewType(sipRes,sipType_QList_0101qt_gui_cpp_PluginDescriptor,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_discover_descriptors, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_load(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_load(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::QString* a0;
        int a0State = 0;
         ::qt_gui_cpp::PluginContext* a1;
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J8", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp, sipType_QString,&a0, &a0State, sipType_qt_gui_cpp_PluginContext, &a1))
        {
            void*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::load(*a0,a1) : sipCpp->load(*a0,a1));
            sipReleaseType(const_cast< ::QString *>(a0),sipType_QString,a0State);

            return sipConvertFromVoidPtr(sipRes);
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_load, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_load_plugin(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_load_plugin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::QString* a0;
        int a0State = 0;
         ::qt_gui_cpp::PluginContext* a1;
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1J8", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp, sipType_QString,&a0, &a0State, sipType_qt_gui_cpp_PluginContext, &a1))
        {
             ::qt_gui_cpp::Plugin*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::load_plugin(*a0,a1) : sipCpp->load_plugin(*a0,a1));
            sipReleaseType(const_cast< ::QString *>(a0),sipType_QString,a0State);

            return sipConvertFromType(sipRes,sipType_qt_gui_cpp_Plugin,SIP_NULLPTR);
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_load_plugin, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_unload(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_unload(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        void* a0;
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bv", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::unload(a0) : sipCpp->unload(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_unload, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_unload_plugin(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_unload_plugin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::qt_gui_cpp::Plugin* a0;
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp, sipType_qt_gui_cpp_Plugin, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::unload_plugin(a0) : sipCpp->unload_plugin(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_unload_plugin, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_qt_gui_cpp_PluginProvider_shutdown(PyObject *, PyObject *);}
static PyObject *meth_qt_gui_cpp_PluginProvider_shutdown(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::qt_gui_cpp::PluginProvider *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_qt_gui_cpp_PluginProvider, &sipCpp))
        {
            (sipSelfWasArg ? sipCpp-> ::qt_gui_cpp::PluginProvider::shutdown() : sipCpp->shutdown());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    sipNoMethod(sipParseErr, sipName_PluginProvider, sipName_shutdown, SIP_NULLPTR);

    return SIP_NULLPTR;
}


/* Call the instance's destructor. */
extern "C" {static void release_qt_gui_cpp_PluginProvider(void *, int);}
static void release_qt_gui_cpp_PluginProvider(void *sipCppV, int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipqt_gui_cpp_PluginProvider *>(sipCppV);
    else
        delete reinterpret_cast< ::qt_gui_cpp::PluginProvider *>(sipCppV);
}


extern "C" {static void *array_qt_gui_cpp_PluginProvider(Py_ssize_t);}
static void *array_qt_gui_cpp_PluginProvider(Py_ssize_t sipNrElem)
{
    return new  ::qt_gui_cpp::PluginProvider[sipNrElem];
}


extern "C" {static void assign_qt_gui_cpp_PluginProvider(void *, SIP_SSIZE_T, void *);}
static void assign_qt_gui_cpp_PluginProvider(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::qt_gui_cpp::PluginProvider *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::qt_gui_cpp::PluginProvider *>(sipSrc);
}


extern "C" {static void *copy_qt_gui_cpp_PluginProvider(const void *, SIP_SSIZE_T);}
static void *copy_qt_gui_cpp_PluginProvider(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::qt_gui_cpp::PluginProvider(reinterpret_cast<const  ::qt_gui_cpp::PluginProvider *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_qt_gui_cpp_PluginProvider(sipSimpleWrapper *);}
static void dealloc_qt_gui_cpp_PluginProvider(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipqt_gui_cpp_PluginProvider *>(sipGetAddress(sipSelf))->sipPySelf = SIP_NULLPTR;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_qt_gui_cpp_PluginProvider(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_qt_gui_cpp_PluginProvider(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_qt_gui_cpp_PluginProvider(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipqt_gui_cpp_PluginProvider *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            sipCpp = new sipqt_gui_cpp_PluginProvider();

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::qt_gui_cpp::PluginProvider* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_qt_gui_cpp_PluginProvider, &a0))
        {
            sipCpp = new sipqt_gui_cpp_PluginProvider(*a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


static PyMethodDef methods_qt_gui_cpp_PluginProvider[] = {
    {SIP_MLNAME_CAST(sipName_discover), meth_qt_gui_cpp_PluginProvider_discover, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_discover_descriptors), meth_qt_gui_cpp_PluginProvider_discover_descriptors, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_load), meth_qt_gui_cpp_PluginProvider_load, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_load_plugin), meth_qt_gui_cpp_PluginProvider_load_plugin, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_shutdown), meth_qt_gui_cpp_PluginProvider_shutdown, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_unload), meth_qt_gui_cpp_PluginProvider_unload, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_unload_plugin), meth_qt_gui_cpp_PluginProvider_unload_plugin, METH_VARARGS, SIP_NULLPTR}
};


static pyqt5ClassPluginDef plugin_qt_gui_cpp_PluginProvider = {
    SIP_NULLPTR,
    0,
    SIP_NULLPTR,
    SIP_NULLPTR
};


sipClassTypeDef sipTypeDef_libqt_gui_cpp_sip_qt_gui_cpp_PluginProvider = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_qt_gui_cpp__PluginProvider,
        {SIP_NULLPTR},
        &plugin_qt_gui_cpp_PluginProvider
    },
    {
        sipNameNr_PluginProvider,
        {3, 255, 0},
        7, methods_qt_gui_cpp_PluginProvider,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    SIP_NULLPTR,
    -1,
    sipNameNr_sip_simplewrapper,
    SIP_NULLPTR,
    SIP_NULLPTR,
    init_type_qt_gui_cpp_PluginProvider,
    SIP_NULLPTR,
    SIP_NULLPTR,
#if PY_MAJOR_VERSION >= 3
    SIP_NULLPTR,
    SIP_NULLPTR,
#else
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
#endif
    dealloc_qt_gui_cpp_PluginProvider,
    assign_qt_gui_cpp_PluginProvider,
    array_qt_gui_cpp_PluginProvider,
    copy_qt_gui_cpp_PluginProvider,
    release_qt_gui_cpp_PluginProvider,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
