# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Accel.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/AccelStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/AccelWithCovariance.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/AccelWithCovarianceStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Inertia.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/InertiaStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Point.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Point32.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/PointStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Polygon.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/PolygonStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Pose2D.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Pose.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/PoseArray.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/PoseStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/PoseWithCovariance.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/PoseWithCovarianceStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Quaternion.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/QuaternionStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Transform.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/TransformStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Twist.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/TwistStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/TwistWithCovariance.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/TwistWithCovarianceStamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Vector3.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Vector3Stamped.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/Wrench.msg;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg/WrenchStamped.msg"
services_str = ""
pkg_name = "geometry_msgs"
dependencies_str = "std_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "geometry_msgs;/home/f1tenthteam2/pleasework/src/common_msgs/geometry_msgs/msg;std_msgs;/home/f1tenthteam2/pleasework/src/std_msgs/msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/home/f1tenthteam2/pleasework/src/genmsg/scripts/genmsg_check_deps.py"
