# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_diagnostic_updater_rostest_test_diagnostic_updater_test.xml "/home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater/test_results/diagnostic_updater/rostest-test_diagnostic_updater_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater --package=diagnostic_updater --results-filename test_diagnostic_updater_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater/test_results\" /home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater/test/diagnostic_updater_test.xml ")
set_tests_properties(_ctest_diagnostic_updater_rostest_test_diagnostic_updater_test.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater/CMakeLists.txt;27;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_updater_rostest_test_diagnostic_updater_fast_test.xml "/home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater/test_results/diagnostic_updater/rostest-test_diagnostic_updater_fast_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater --package=diagnostic_updater --results-filename test_diagnostic_updater_fast_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/diagnostic_updater/test_results\" /home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater/test/diagnostic_updater_fast_test.xml ")
set_tests_properties(_ctest_diagnostic_updater_rostest_test_diagnostic_updater_fast_test.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater/CMakeLists.txt;28;add_rostest;/home/f1tenthteam2/pleasework/src/diagnostics/diagnostic_updater/CMakeLists.txt;0;")
subdirs("gtest")
