# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/resource_retriever/test
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/resource_retriever/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_resource_retriever_gtest_resource_retriever_utest "/home/f1tenthteam2/pleasework/build_isolated/resource_retriever/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/resource_retriever/test_results/resource_retriever/gtest-resource_retriever_utest.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/resource_retriever/lib/resource_retriever/resource_retriever_utest --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/resource_retriever/test_results/resource_retriever/gtest-resource_retriever_utest.xml")
set_tests_properties(_ctest_resource_retriever_gtest_resource_retriever_utest PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/resource_retriever/test/CMakeLists.txt;3;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/resource_retriever/test/CMakeLists.txt;0;")
add_test(_ctest_resource_retriever_nosetests_test.py "/home/f1tenthteam2/pleasework/build_isolated/resource_retriever/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/resource_retriever/test_results/resource_retriever/nosetests-test.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/f1tenthteam2/pleasework/build_isolated/resource_retriever/test_results/resource_retriever" "/usr/bin/nosetests3 -P --process-timeout=60 /home/f1tenthteam2/pleasework/src/resource_retriever/test/test.py --with-xunit --xunit-file=/home/f1tenthteam2/pleasework/build_isolated/resource_retriever/test_results/resource_retriever/nosetests-test.py.xml")
set_tests_properties(_ctest_resource_retriever_nosetests_test.py PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/resource_retriever/test/CMakeLists.txt;6;catkin_add_nosetests;/home/f1tenthteam2/pleasework/src/resource_retriever/test/CMakeLists.txt;0;")
