# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_dynamic_reconfigure_rostest_test_test_cpp_client_single_threaded.test "/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test_results/dynamic_reconfigure/rostest-test_test_cpp_client_single_threaded.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/dynamic_reconfigure --package=dynamic_reconfigure --results-filename test_test_cpp_client_single_threaded.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test_results\" /home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/test_cpp_client_single_threaded.test ")
set_tests_properties(_ctest_dynamic_reconfigure_rostest_test_test_cpp_client_single_threaded.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/CMakeLists.txt;1;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/CMakeLists.txt;0;")
add_test(_ctest_dynamic_reconfigure_rostest_test_test_cpp_simple_client.launch "/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test_results/dynamic_reconfigure/rostest-test_test_cpp_simple_client.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/dynamic_reconfigure --package=dynamic_reconfigure --results-filename test_test_cpp_simple_client.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test_results\" /home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/test_cpp_simple_client.launch ")
set_tests_properties(_ctest_dynamic_reconfigure_rostest_test_test_cpp_simple_client.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/CMakeLists.txt;13;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/CMakeLists.txt;0;")
add_test(_ctest_dynamic_reconfigure_rostest_test_test_python_simple_client.launch "/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test_results/dynamic_reconfigure/rostest-test_test_python_simple_client.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/dynamic_reconfigure --package=dynamic_reconfigure --results-filename test_test_python_simple_client.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/dynamic_reconfigure/test_results\" /home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/test_python_simple_client.launch ")
set_tests_properties(_ctest_dynamic_reconfigure_rostest_test_test_python_simple_client.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/CMakeLists.txt;19;add_rostest;/home/f1tenthteam2/pleasework/src/dynamic_reconfigure/test/CMakeLists.txt;0;")
