set(_CATKIN_CURRENT_PACKAGE "rqt_publisher")
set(rqt_publisher_VERSION "0.4.10")
set(rqt_publisher_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(rqt_publisher_PACKAGE_FORMAT "3")
set(rqt_publisher_BUILD_DEPENDS )
set(rqt_publisher_BUILD_EXPORT_DEPENDS )
set(rqt_publisher_BUILDTOOL_DEPENDS "catkin")
set(rqt_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_publisher_EXEC_DEPENDS "python-rospkg" "python3-rospkg" "python_qt_binding" "qt_gui_py_common" "roslib" "rosmsg" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_publisher_EXEC_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_publisher_EXEC_DEPENDS_rosmsg_VERSION_GTE "1.9.49")
set(rqt_publisher_RUN_DEPENDS "python-rospkg" "python3-rospkg" "python_qt_binding" "qt_gui_py_common" "roslib" "rosmsg" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_publisher_RUN_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_publisher_RUN_DEPENDS_rosmsg_VERSION_GTE "1.9.49")
set(rqt_publisher_TEST_DEPENDS )
set(rqt_publisher_DOC_DEPENDS )
set(rqt_publisher_URL_WEBSITE "http://wiki.ros.org/rqt_publisher")
set(rqt_publisher_URL_BUGTRACKER "https://github.com/ros-visualization/rqt_publisher/issues")
set(rqt_publisher_URL_REPOSITORY "https://github.com/ros-visualization/rqt_publisher")
set(rqt_publisher_DEPRECATED "")