# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_joint_limits_interface_gtest_joint_limits_interface_test "/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_interface_test.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/joint_limits_interface/lib/joint_limits_interface/joint_limits_interface_test --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_interface_test.xml")
set_tests_properties(_ctest_joint_limits_interface_gtest_joint_limits_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/CMakeLists.txt;37;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/CMakeLists.txt;0;")
add_test(_ctest_joint_limits_interface_gtest_joint_limits_urdf_test "/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_urdf_test.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/joint_limits_interface/lib/joint_limits_interface/joint_limits_urdf_test --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_urdf_test.xml")
set_tests_properties(_ctest_joint_limits_interface_gtest_joint_limits_urdf_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/CMakeLists.txt;40;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/CMakeLists.txt;0;")
add_test(_ctest_joint_limits_interface_rostest_test_joint_limits_rosparam.test "/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/test_results/joint_limits_interface/rostest-test_joint_limits_rosparam.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface --package=joint_limits_interface --results-filename test_joint_limits_rosparam.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/joint_limits_interface/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/test/joint_limits_rosparam.test ")
set_tests_properties(_ctest_joint_limits_interface_rostest_test_joint_limits_rosparam.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/CMakeLists.txt;43;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/ros_control/joint_limits_interface/CMakeLists.txt;0;")
subdirs("gtest")
