set(_CATKIN_CURRENT_PACKAGE "vesc_driver")
set(vesc_driver_VERSION "1.1.0")
set(vesc_driver_MAINTAINER "Johannes Betz <joebetz@seas.upenn.edu>")
set(vesc_driver_PACKAGE_FORMAT "3")
set(vesc_driver_BUILD_DEPENDS "roslint" "nodelet" "pluginlib" "roscpp" "serial" "std_msgs" "vesc_msgs")
set(vesc_driver_BUILD_EXPORT_DEPENDS "nodelet" "pluginlib" "roscpp" "serial" "std_msgs" "vesc_msgs")
set(vesc_driver_BUILDTOOL_DEPENDS "catkin")
set(vesc_driver_BUILDTOOL_EXPORT_DEPENDS )
set(vesc_driver_EXEC_DEPENDS "nodelet" "pluginlib" "roscpp" "serial" "std_msgs" "vesc_msgs")
set(vesc_driver_RUN_DEPENDS "nodelet" "pluginlib" "roscpp" "serial" "std_msgs" "vesc_msgs")
set(vesc_driver_TEST_DEPENDS )
set(vesc_driver_DOC_DEPENDS )
set(vesc_driver_URL_WEBSITE "http://www.ros.org/wiki/vesc_driver")
set(vesc_driver_URL_BUGTRACKER "https://github.com/f1tenth/vesc/issues")
set(vesc_driver_URL_REPOSITORY "https://github.com/f1tenth/vesc")
set(vesc_driver_DEPRECATED "")