# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/class_loader/test
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/class_loader/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_class_loader_gtest_class_loader_utest "/home/f1tenthteam2/pleasework/build_isolated/class_loader/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/class_loader/test_results/class_loader/gtest-class_loader_utest.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/class_loader/lib/class_loader/class_loader_utest --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/class_loader/test_results/class_loader/gtest-class_loader_utest.xml")
set_tests_properties(_ctest_class_loader_gtest_class_loader_utest PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/class_loader/test/CMakeLists.txt;27;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/class_loader/test/CMakeLists.txt;0;")
add_test(_ctest_class_loader_gtest_class_loader_shared_ptr_test "/home/f1tenthteam2/pleasework/build_isolated/class_loader/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/class_loader/test_results/class_loader/gtest-class_loader_shared_ptr_test.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/class_loader/lib/class_loader/class_loader_shared_ptr_test --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/class_loader/test_results/class_loader/gtest-class_loader_shared_ptr_test.xml")
set_tests_properties(_ctest_class_loader_gtest_class_loader_shared_ptr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/class_loader/test/CMakeLists.txt;33;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/class_loader/test/CMakeLists.txt;0;")
add_test(_ctest_class_loader_gtest_class_loader_unique_ptr_test "/home/f1tenthteam2/pleasework/build_isolated/class_loader/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/class_loader/test_results/class_loader/gtest-class_loader_unique_ptr_test.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/class_loader/lib/class_loader/class_loader_unique_ptr_test --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/class_loader/test_results/class_loader/gtest-class_loader_unique_ptr_test.xml")
set_tests_properties(_ctest_class_loader_gtest_class_loader_unique_ptr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/class_loader/test/CMakeLists.txt;39;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/class_loader/test/CMakeLists.txt;0;")
