# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/angles/test
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/angles/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_angles_gtest_utest "/home/f1tenthteam2/pleasework/build_isolated/angles/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/angles/test_results/angles/gtest-utest.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/angles/lib/angles/utest --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/angles/test_results/angles/gtest-utest.xml")
set_tests_properties(_ctest_angles_gtest_utest PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/angles/test/CMakeLists.txt;2;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/angles/test/CMakeLists.txt;0;")
add_test(_ctest_angles_nosetests_utest.py "/home/f1tenthteam2/pleasework/build_isolated/angles/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/angles/test_results/angles/nosetests-utest.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/f1tenthteam2/pleasework/build_isolated/angles/test_results/angles" "/usr/bin/nosetests3 -P --process-timeout=60 /home/f1tenthteam2/pleasework/src/angles/test/utest.py --with-xunit --xunit-file=/home/f1tenthteam2/pleasework/build_isolated/angles/test_results/angles/nosetests-utest.py.xml")
set_tests_properties(_ctest_angles_nosetests_utest.py PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/angles/test/CMakeLists.txt;3;catkin_add_nosetests;/home/f1tenthteam2/pleasework/src/angles/test/CMakeLists.txt;0;")
