# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/geometry/tf_conversions
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/tf_conversions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf_conversions_gtest_test_eigen_tf "/home/f1tenthteam2/pleasework/build_isolated/tf_conversions/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_eigen_tf.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/tf_conversions/lib/tf_conversions/test_eigen_tf --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_eigen_tf.xml")
set_tests_properties(_ctest_tf_conversions_gtest_test_eigen_tf PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/geometry/tf_conversions/CMakeLists.txt;33;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/geometry/tf_conversions/CMakeLists.txt;0;")
add_test(_ctest_tf_conversions_gtest_test_kdl_tf "/home/f1tenthteam2/pleasework/build_isolated/tf_conversions/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_kdl_tf.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/tf_conversions/lib/tf_conversions/test_kdl_tf --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_kdl_tf.xml")
set_tests_properties(_ctest_tf_conversions_gtest_test_kdl_tf PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/geometry/tf_conversions/CMakeLists.txt;36;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/geometry/tf_conversions/CMakeLists.txt;0;")
subdirs("gtest")
