# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_controller_manager_tests_rostest_test_cm_test.test "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_cm_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_cm_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/test/cm_test.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_cm_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;50;add_rostest;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_cm_msgs_utils_rostest.test "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_cm_msgs_utils_rostest.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_cm_msgs_utils_rostest.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_cm_msgs_utils_rostest.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;52;add_rostest;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_controller_manager_scripts.test "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_controller_manager_scripts.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_controller_manager_scripts.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/test/controller_manager_scripts.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_controller_manager_scripts.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;54;add_rostest;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_controller_manager_interface_test.test "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_controller_manager_interface_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_controller_manager_interface_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/controller_manager_tests/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/test/controller_manager_interface_test.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_controller_manager_interface_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;56;add_rostest;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
subdirs("gtest")
