set(_CATKIN_CURRENT_PACKAGE "vesc_msgs")
set(vesc_msgs_VERSION "1.1.0")
set(vesc_msgs_MAINTAINER "Johannes Betz <joebetz@seas.upenn.edu>")
set(vesc_msgs_PACKAGE_FORMAT "3")
set(vesc_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(vesc_msgs_BUILD_EXPORT_DEPENDS "std_msgs")
set(vesc_msgs_BUILDTOOL_DEPENDS "catkin")
set(vesc_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(vesc_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(vesc_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(vesc_msgs_TEST_DEPENDS )
set(vesc_msgs_DOC_DEPENDS )
set(vesc_msgs_URL_WEBSITE "http://ros.org/wiki/vesc_msgs")
set(vesc_msgs_URL_BUGTRACKER "https://github.com/f1tenth/vesc/issues")
set(vesc_msgs_URL_REPOSITORY "https://github.com/f1tenth/vesc")
set(vesc_msgs_DEPRECATED "")