# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/rqt_reconfigure
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rqt_reconfigure_roslint_package "/home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/test_results/rqt_reconfigure/roslint-rqt_reconfigure.xml" "--working-dir" "/home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure" "--return-code" "/home/f1tenthteam2/pleasework/src/roslint/scripts/test_wrapper /home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/test_results/rqt_reconfigure/roslint-rqt_reconfigure.xml make roslint_rqt_reconfigure")
set_tests_properties(_ctest_rqt_reconfigure_roslint_package PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/roslint/share/roslint/cmake/roslint-extras.cmake;67;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/rqt_reconfigure/CMakeLists.txt;24;roslint_add_test;/home/f1tenthteam2/pleasework/src/rqt_reconfigure/CMakeLists.txt;0;")
add_test(_ctest_rqt_reconfigure_nosetests_test "/home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/test_results/rqt_reconfigure/nosetests-test.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/test_results/rqt_reconfigure" "/usr/bin/nosetests3 -P --process-timeout=60 --where=/home/f1tenthteam2/pleasework/src/rqt_reconfigure/test --with-xunit --xunit-file=/home/f1tenthteam2/pleasework/build_isolated/rqt_reconfigure/test_results/rqt_reconfigure/nosetests-test.xml")
set_tests_properties(_ctest_rqt_reconfigure_nosetests_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/rqt_reconfigure/CMakeLists.txt;25;catkin_add_nosetests;/home/f1tenthteam2/pleasework/src/rqt_reconfigure/CMakeLists.txt;0;")
subdirs("gtest")
