set(_CATKIN_CURRENT_PACKAGE "rqt_service_caller")
set(rqt_service_caller_VERSION "0.4.10")
set(rqt_service_caller_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(rqt_service_caller_PACKAGE_FORMAT "3")
set(rqt_service_caller_BUILD_DEPENDS )
set(rqt_service_caller_BUILD_EXPORT_DEPENDS )
set(rqt_service_caller_BUILDTOOL_DEPENDS "catkin")
set(rqt_service_caller_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_service_caller_EXEC_DEPENDS "python-rospkg" "python3-rospkg" "rosservice" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_service_caller_RUN_DEPENDS "python-rospkg" "python3-rospkg" "rosservice" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_service_caller_TEST_DEPENDS )
set(rqt_service_caller_DOC_DEPENDS )
set(rqt_service_caller_URL_WEBSITE "http://wiki.ros.org/rqt_service_caller")
set(rqt_service_caller_URL_BUGTRACKER "https://github.com/ros-visualization/rqt_service_caller/issues")
set(rqt_service_caller_URL_REPOSITORY "https://github.com/ros-visualization/rqt_service_caller")
set(rqt_service_caller_DEPRECATED "")