set(_CATKIN_CURRENT_PACKAGE "vesc")
set(vesc_VERSION "1.1.0")
set(vesc_MAINTAINER "Johannes Betz <joebetz@seas.upenn.edu>")
set(vesc_PACKAGE_FORMAT "3")
set(vesc_BUILD_DEPENDS )
set(vesc_BUILD_EXPORT_DEPENDS )
set(vesc_BUILDTOOL_DEPENDS "catkin")
set(vesc_BUILDTOOL_EXPORT_DEPENDS )
set(vesc_EXEC_DEPENDS "vesc_driver" "vesc_msgs" "vesc_ackermann")
set(vesc_RUN_DEPENDS "vesc_driver" "vesc_msgs" "vesc_ackermann")
set(vesc_TEST_DEPENDS )
set(vesc_DOC_DEPENDS )
set(vesc_URL_WEBSITE "http://www.ros.org/wiki/vesc")
set(vesc_URL_BUGTRACKER "https://github.com/f1tenth/vesc/issues")
set(vesc_URL_REPOSITORY "https://github.com/f1tenth/vesc")
set(vesc_DEPRECATED "")