set(_CATKIN_CURRENT_PACKAGE "rqt_top")
set(rqt_top_VERSION "0.4.10")
set(rqt_top_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(rqt_top_PACKAGE_FORMAT "3")
set(rqt_top_BUILD_DEPENDS )
set(rqt_top_BUILD_EXPORT_DEPENDS )
set(rqt_top_BUILDTOOL_DEPENDS "catkin")
set(rqt_top_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_top_EXEC_DEPENDS "python-psutil" "python3-psutil" "python_qt_binding" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_top_EXEC_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_top_RUN_DEPENDS "python-psutil" "python3-psutil" "python_qt_binding" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_top_RUN_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_top_TEST_DEPENDS )
set(rqt_top_DOC_DEPENDS )
set(rqt_top_URL_WEBSITE "http://wiki.ros.org/rqt_top")
set(rqt_top_URL_BUGTRACKER "https://github.com/ros-visualization/rqt_top/issues")
set(rqt_top_URL_REPOSITORY "https://github.com/ros-visualization/rqt_top")
set(rqt_top_DEPRECATED "")