set(_CATKIN_CURRENT_PACKAGE "rqt_msg")
set(rqt_msg_VERSION "0.4.10")
set(rqt_msg_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(rqt_msg_PACKAGE_FORMAT "3")
set(rqt_msg_BUILD_DEPENDS )
set(rqt_msg_BUILD_EXPORT_DEPENDS )
set(rqt_msg_BUILDTOOL_DEPENDS "catkin")
set(rqt_msg_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_msg_EXEC_DEPENDS "python-rospkg" "python3-rospkg" "python_qt_binding" "roslib" "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "rqt_console")
set(rqt_msg_EXEC_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_msg_RUN_DEPENDS "python-rospkg" "python3-rospkg" "python_qt_binding" "roslib" "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "rqt_console")
set(rqt_msg_RUN_DEPENDS_python_qt_binding_VERSION_GTE "0.2.19")
set(rqt_msg_TEST_DEPENDS )
set(rqt_msg_DOC_DEPENDS )
set(rqt_msg_URL_WEBSITE "http://wiki.ros.org/rqt_msg")
set(rqt_msg_URL_BUGTRACKER "https://github.com/ros-visualization/rqt_msg/issues")
set(rqt_msg_URL_REPOSITORY "https://github.com/ros-visualization/rqt_msg")
set(rqt_msg_DEPRECATED "")