# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/catkin
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/catkin
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_catkin_nosetests_test.local_tests "/home/f1tenthteam2/pleasework/build_isolated/catkin/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/catkin/test_results/catkin/nosetests-test.local_tests.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/f1tenthteam2/pleasework/build_isolated/catkin/test_results/catkin" "/usr/bin/nosetests3 -P --process-timeout=60 --where=/home/f1tenthteam2/pleasework/src/catkin/test/local_tests --with-xunit --xunit-file=/home/f1tenthteam2/pleasework/build_isolated/catkin/test_results/catkin/nosetests-test.local_tests.xml")
set_tests_properties(_ctest_catkin_nosetests_test.local_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/CMakeLists.txt;26;catkin_add_nosetests;/home/f1tenthteam2/pleasework/src/catkin/CMakeLists.txt;0;")
add_test(_ctest_catkin_nosetests_test.unit_tests "/home/f1tenthteam2/pleasework/build_isolated/catkin/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/catkin/test_results/catkin/nosetests-test.unit_tests.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/f1tenthteam2/pleasework/build_isolated/catkin/test_results/catkin" "/usr/bin/nosetests3 -P --process-timeout=60 --where=/home/f1tenthteam2/pleasework/src/catkin/test/unit_tests --with-xunit --xunit-file=/home/f1tenthteam2/pleasework/build_isolated/catkin/test_results/catkin/nosetests-test.unit_tests.xml")
set_tests_properties(_ctest_catkin_nosetests_test.unit_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/CMakeLists.txt;27;catkin_add_nosetests;/home/f1tenthteam2/pleasework/src/catkin/CMakeLists.txt;0;")
subdirs("gtest")
