# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_combined_robot_hw_tests_rostest_test_combined_robot_hw_test.test "/home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests/test_results/combined_robot_hw_tests/rostest-test_combined_robot_hw_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests --package=combined_robot_hw_tests --results-filename test_combined_robot_hw_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests/test/combined_robot_hw_test.test ")
set_tests_properties(_ctest_combined_robot_hw_tests_rostest_test_combined_robot_hw_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;40;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;0;")
add_test(_ctest_combined_robot_hw_tests_rostest_test_cm_test.test "/home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests/test_results/combined_robot_hw_tests/rostest-test_cm_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests --package=combined_robot_hw_tests --results-filename test_cm_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/combined_robot_hw_tests/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests/test/cm_test.test ")
set_tests_properties(_ctest_combined_robot_hw_tests_rostest_test_cm_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;46;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;0;")
subdirs("gtest")
