# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/ros_control/controller_manager
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/controller_manager
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_controller_manager_rostest_test_hwi_switch_test.test "/home/f1tenthteam2/pleasework/build_isolated/controller_manager/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/controller_manager/test_results/controller_manager/rostest-test_hwi_switch_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/controller_manager --package=controller_manager --results-filename test_hwi_switch_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/controller_manager/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/controller_manager/test/hwi_switch_test.test ")
set_tests_properties(_ctest_controller_manager_rostest_test_hwi_switch_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager/CMakeLists.txt;54;add_rostest_gtest;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_rostest_test_hwi_update_test.test "/home/f1tenthteam2/pleasework/build_isolated/controller_manager/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/controller_manager/test_results/controller_manager/rostest-test_hwi_update_test.xml" "--return-code" "/usr/bin/python3 /home/f1tenthteam2/pleasework/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/f1tenthteam2/pleasework/src/ros_control/controller_manager --package=controller_manager --results-filename test_hwi_update_test.xml --results-base-dir \"/home/f1tenthteam2/pleasework/build_isolated/controller_manager/test_results\" /home/f1tenthteam2/pleasework/src/ros_control/controller_manager/test/hwi_update_test.test ")
set_tests_properties(_ctest_controller_manager_rostest_test_hwi_update_test.test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/f1tenthteam2/pleasework/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;119;_add_rostest_google_test;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager/CMakeLists.txt;61;add_rostest_gmock;/home/f1tenthteam2/pleasework/src/ros_control/controller_manager/CMakeLists.txt;0;")
subdirs("gtest")
