# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/ros/roslib
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/roslib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_roslib_nosetests_test "/home/f1tenthteam2/pleasework/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib/nosetests-test.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib" "/usr/bin/nosetests3 -P --process-timeout=60 --where=/home/f1tenthteam2/pleasework/src/ros/roslib/test --with-xunit --xunit-file=/home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib/nosetests-test.xml")
set_tests_properties(_ctest_roslib_nosetests_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/ros/roslib/CMakeLists.txt;42;catkin_add_nosetests;/home/f1tenthteam2/pleasework/src/ros/roslib/CMakeLists.txt;0;")
add_test(_ctest_roslib_gtest_roslib-utest "/home/f1tenthteam2/pleasework/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml" "--working-dir" "/home/f1tenthteam2/pleasework/src/ros/roslib" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/roslib/lib/roslib/roslib-utest --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml")
set_tests_properties(_ctest_roslib_gtest_roslib-utest PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/ros/roslib/CMakeLists.txt;44;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/ros/roslib/CMakeLists.txt;0;")
add_test(_ctest_roslib_gtest_roslib-test_package "/home/f1tenthteam2/pleasework/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/roslib/lib/roslib/roslib-test_package --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml")
set_tests_properties(_ctest_roslib_gtest_roslib-test_package PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/ros/roslib/CMakeLists.txt;49;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/ros/roslib/CMakeLists.txt;0;")
subdirs("gtest")
