# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/urg_node-melodic-devel
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/urg_node
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_urg_node_roslint_package "/home/f1tenthteam2/pleasework/build_isolated/urg_node/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/urg_node/test_results/urg_node/roslint-urg_node.xml" "--working-dir" "/home/f1tenthteam2/pleasework/build_isolated/urg_node" "--return-code" "/home/f1tenthteam2/pleasework/src/roslint/scripts/test_wrapper /home/f1tenthteam2/pleasework/build_isolated/urg_node/test_results/urg_node/roslint-urg_node.xml make roslint_urg_node")
set_tests_properties(_ctest_urg_node_roslint_package PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/roslint/share/roslint/cmake/roslint-extras.cmake;67;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/urg_node-melodic-devel/CMakeLists.txt;90;roslint_add_test;/home/f1tenthteam2/pleasework/src/urg_node-melodic-devel/CMakeLists.txt;0;")
add_test(_ctest_urg_node_roslaunch-check_launch_urg_lidar.launch "/home/f1tenthteam2/pleasework/build_isolated/urg_node/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/urg_node/test_results/urg_node/roslaunch-check_launch_urg_lidar.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/f1tenthteam2/pleasework/build_isolated/urg_node/test_results/urg_node" "/home/f1tenthteam2/pleasework/src/ros_comm/roslaunch/scripts/roslaunch-check -o \"/home/f1tenthteam2/pleasework/build_isolated/urg_node/test_results/urg_node/roslaunch-check_launch_urg_lidar.launch.xml\" \"/home/f1tenthteam2/pleasework/src/urg_node-melodic-devel/launch/urg_lidar.launch\" ")
set_tests_properties(_ctest_urg_node_roslaunch-check_launch_urg_lidar.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/devel_isolated/roslaunch/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/urg_node-melodic-devel/CMakeLists.txt;93;roslaunch_add_file_check;/home/f1tenthteam2/pleasework/src/urg_node-melodic-devel/CMakeLists.txt;0;")
subdirs("gtest")
