# CMake generated Testfile for 
# Source directory: /home/f1tenthteam2/pleasework/src/common_msgs/sensor_msgs/test
# Build directory: /home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_sensor_msgs_gtest_sensor_msgs_test "/home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/test_results/sensor_msgs/gtest-sensor_msgs_test.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/sensor_msgs/lib/sensor_msgs/sensor_msgs_test --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/test_results/sensor_msgs/gtest-sensor_msgs_test.xml")
set_tests_properties(_ctest_sensor_msgs_gtest_sensor_msgs_test PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/common_msgs/sensor_msgs/test/CMakeLists.txt;2;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/common_msgs/sensor_msgs/test/CMakeLists.txt;0;")
add_test(_ctest_sensor_msgs_gtest_sensor_msgs_test_image_encodings "/home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/run_tests.py" "/home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/test_results/sensor_msgs/gtest-sensor_msgs_test_image_encodings.xml" "--return-code" "/home/f1tenthteam2/pleasework/devel_isolated/sensor_msgs/lib/sensor_msgs/sensor_msgs_test_image_encodings --gtest_output=xml:/home/f1tenthteam2/pleasework/build_isolated/sensor_msgs/test_results/sensor_msgs/gtest-sensor_msgs_test_image_encodings.xml")
set_tests_properties(_ctest_sensor_msgs_gtest_sensor_msgs_test_image_encodings PROPERTIES  _BACKTRACE_TRIPLES "/home/f1tenthteam2/pleasework/src/catkin/cmake/test/tests.cmake;160;add_test;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/f1tenthteam2/pleasework/src/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/f1tenthteam2/pleasework/src/common_msgs/sensor_msgs/test/CMakeLists.txt;3;catkin_add_gtest;/home/f1tenthteam2/pleasework/src/common_msgs/sensor_msgs/test/CMakeLists.txt;0;")
