set(_CATKIN_CURRENT_PACKAGE "resource_retriever")
set(resource_retriever_VERSION "1.12.7")
set(resource_retriever_MAINTAINER "Chris Lalancette <clalancette@osrfoundation.org>, Shane Loretz <sloretz@osrfoundation.org>")
set(resource_retriever_PACKAGE_FORMAT "3")
set(resource_retriever_BUILD_DEPENDS "libcurl-dev" "roslib" "rosconsole" "boost")
set(resource_retriever_BUILD_EXPORT_DEPENDS "roslib" "rosconsole" "boost")
set(resource_retriever_BUILDTOOL_DEPENDS "catkin")
set(resource_retriever_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(resource_retriever_BUILDTOOL_EXPORT_DEPENDS )
set(resource_retriever_EXEC_DEPENDS "libcurl" "python-rospkg" "python3-rospkg" "roslib" "rosconsole" "boost")
set(resource_retriever_RUN_DEPENDS "libcurl" "python-rospkg" "python3-rospkg" "roslib" "rosconsole" "boost")
set(resource_retriever_TEST_DEPENDS )
set(resource_retriever_DOC_DEPENDS )
set(resource_retriever_URL_WEBSITE "http://ros.org/wiki/resource_retriever")
set(resource_retriever_URL_BUGTRACKER "https://github.com/ros/resource_retriever/issues")
set(resource_retriever_URL_REPOSITORY "https://github.com/ros/resource_retriever")
set(resource_retriever_DEPRECATED "")